package com.qianfeng.application.dao;

import com.qianfeng.application.model.Org;
import com.qianfeng.application.model.Orgs;

import java.util.List;
import java.util.Map;

public interface OrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Thu Jan 03 17:25:18 CST 2019
     */
    int deleteByPrimaryKey(Long orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Thu Jan 03 17:25:18 CST 2019
     */
    int insert(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Thu Jan 03 17:25:18 CST 2019
     */
    int insertSelective(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Thu Jan 03 17:25:18 CST 2019
     */
    Org selectByPrimaryKey(Long orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Thu Jan 03 17:25:18 CST 2019
     */
    int updateByPrimaryKeySelective(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Thu Jan 03 17:25:18 CST 2019
     */
    int updateByPrimaryKey(Org record);

    List<Org> queryOrgListByOrgParentId(Map<String, Object> map);

    /*查询组织的分页数据*/
    List<Org> queryOrgList(Map<String, Object> paramMap);
    /*查询组织的总条数*/
    int queryOrgTotal(Map<String, Object> paramMap);

    Orgs getOrgByOrgId(int orgId);
}