package com.qianfeng.application.dao;

import com.qianfeng.application.model.User;
import com.qianfeng.application.model.Users;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Jan 04 16:06:44 CST 2019
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Jan 04 16:06:44 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Jan 04 16:06:44 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Jan 04 16:06:44 CST 2019
     */
    User selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Jan 04 16:06:44 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Fri Jan 04 16:06:44 CST 2019
     */
    int updateByPrimaryKey(User record);
    /* 查询用户的分页数据*/
    List<User> getUserList(Map<String, Object> paramMap);
    /* 查询用户的分页总条数*/
    int getUserTotal(Map<String, Object> paramMap);

    Users getUserByUserId(int userId);
}